### PR TITLE
completed chapter 5 and intermission

### PR DESCRIPTION
**Pull request by Js791**

### CODE REVIEW

**Comment by jtoar** [comment]
Hey @Js791, mind elaborating a bit here? This isn't supposed to include any content from chapter 5 because you're supposed to pick up this repo at the intermissions. But if there's errors related to chapter 4 or something like that, happy to make those amends.

**Comment by Js791** [comment]
> Hey @Js791, mind elaborating a bit here? This isn't supposed to include any content from chapter 5 because you're supposed to pick up this repo at the intermissions. But if there's errors related to chapter 4 or something like that, happy to make those amends.

@jtoar I have a college course teaching us redwoodjs. The assignment was the redwood tutorial, I wanted to copy the example repo and finish the tutorial using the example repo as a baseline. I guess I performed the copying part incorrectly and modified the original?

**Comment by jtoar** [comment]
>  I have a college course teaching us redwoodjs

Very cool! :rocket:

You haven't modified the original yet, but by opening a pull request against it, you're trying to. Maybe you meant to make a pull request against your fork only and not the redwood-tutorial itself?

**Comment by Js791** [comment]
> > I have a college course teaching us redwoodjs
> 
> Very cool! 🚀
> 
> You haven't modified the original yet, but by opening a pull request against it, you're trying to. Maybe you meant to make a pull request against your fork only and not the redwood-tutorial itself?

@jtoar yeah this was what I was attempting to do.

**Pull request closed without merging**
